### ISSUE TITLE
RegistIssue의 인자 순서가 연동메뉴얼과 다른 부분이 있습니다

### ISSUE THREAD

**Issue by malangfox** [linkhub-sdk/node-popbill#2]
https://docs.popbill.com/taxinvoice/java/api#RegistIssue 의 연동 메뉴얼에서는 RegistIssue의 4번째 인자로 Memo, 5번째 인자로 Forceissue를 받고 있습니다.

https://github.com/linkhub-sdk/node-popbill/blob/1470ab59f977f9b2e895686e89848d46bab48edd/lib/TaxinvoiceService.js#L1142

하지만 위 RegistIssue에서는 4번째 인자로 Forceissue를, 5번째 인자로 Memo를 받고 있어서 연동메뉴얼대로 개발하였을 시 문제가 발생하게 됩니다.

혼동을 방지하기 위해 연동메뉴얼의 갱신이 필요할 것 같습니다.

**Comment by JohnJeong123** [comment]
@ahn3407 

연동매뉴얼을 잘못 참조하고 계시네요. Java 연동매뉴얼이 아닌 node.js 연동매뉴얼을 참조하시기 바랍니다. 

https://docs.popbill.com/taxinvoice/node/api#RegistIssue

**Comment by malangfox** [comment]
확인 완료하였습니다. 감사합니다.

**Comment by malangfox** [comment]
혹시 https://docs.popbill.com/taxinvoice/node/api#TIissue 에 있는 5번째 인자 EmailSubject와  6번째 인자 ForceIssue 와 관련하여 

https://github.com/linkhub-sdk/node-popbill/blob/1470ab59f977f9b2e895686e89848d46bab48edd/lib/TaxinvoiceService.js#L530

위 부분에도 이상이 없는지 확인이 가능할까요?

**Comment by JohnJeong123** [comment]
@ahn3407 

연동매뉴얼은 해당함수의 오버로딩하여 최종적으로 호출되는 함수를 설명하고 있습니다. 

https://github.com/linkhub-sdk/node-popbill/blob/1470ab59f977f9b2e895686e89848d46bab48edd/lib/TaxinvoiceService.js#L534
