### ISSUE TITLE
typescript 로 바꾸기

### ISSUE THREAD

**Issue by dev-solid-desktop** [linkhub-sdk/node-popbill#3]
TS 로 바꾸면 사용하는 입장에서나 라이브러리 만드는 입장에서 좋을 것 같습니다
(오타 등 방지 / 자동완성 도움받기 등)

**Comment by JohnJeong123** [comment]
@dev-solid-desktop 
코멘트 감사합니다. 검토해보도록 하겠습니다 : )

**Comment by narumir** [comment]
혹시 적어도 d.ts 지원 예정이 있을까요???
